#!/usr/bin/env python3
"""
Translate SVG diagrams from English to German.
"""

import os
import re
from pathlib import Path

PROJECT_DIR = Path(__file__).parent.parent

# Translation dictionary - English to German
TRANSLATIONS = {
    # Diagram subtitles (longer phrases first)
    "A systematic approach to fixing errors with AI": "Ein systematischer Ansatz zur Fehlerbehebung mit KI",
    "The fundamental partnership between human and AI": "Die fundamentale Partnerschaft zwischen Mensch und KI",
    "The fundamental rhythm of AI-assisted development": "Der fundamentale Rhythmus KI-gestützter Entwicklung",
    "First attempt rarely perfect—that's normal": "Erster Versuch selten perfekt—das ist normal",
    "Everything you can do with AI": "Alles, was du mit KI tun kannst",
    "Breaking big problems into AI-sized pieces": "Große Probleme in KI-gerechte Teile zerlegen",
    "If you can't describe it in one sentence, it's too big": "Wenn du es nicht in einem Satz beschreiben kannst, ist es zu groß",
    "From vague to precise—where better prompts live": "Von vage zu präzise—wo bessere Prompts leben",
    "The five parts of an effective prompt": "Die fünf Teile eines effektiven Prompts",
    "How you respond determines what you get next": "Wie du antwortest bestimmt, was du als Nächstes bekommst",
    "The correction formula that works": "Die Korrekturformel, die funktioniert",
    "What AI can and cannot see": "Was KI sehen kann und was nicht",
    "Types of context to include": "Arten von Kontext zum Einschließen",
    "When to abandon and start fresh": "Wann aufgeben und neu anfangen",
    "The 5-attempt rule for knowing when to reset": "Die 5-Versuch-Regel um zu wissen, wann man neu startet",
    "Mistakes beginners make with AI coding": "Fehler, die Anfänger beim KI-Programmieren machen",
    "How much to trust AI output in different contexts": "Wie viel man KI-Ausgaben in verschiedenen Kontexten vertrauen sollte",
    "Know your errors": "Kenne deine Fehler",
    "Recognizing when you're spinning your wheels": "Erkennen, wenn du dich im Kreis drehst",
    "Six ways to get unstuck": "Sechs Wege, um weiterzukommen",
    "What to focus on when reading code": "Worauf man beim Code-Lesen achten sollte",
    "The universal parts of any program": "Die universellen Teile jedes Programms",
    "Named containers for data": "Benannte Behälter für Daten",
    "How programs make decisions and repeat": "Wie Programme Entscheidungen treffen und wiederholen",
    "Reusable blocks of code": "Wiederverwendbare Code-Bausteine",
    "Standing on the shoulders of giants": "Auf den Schultern von Riesen stehen",
    "How to organize your data": "Wie man seine Daten organisiert",
    "Permanent storage for your programs": "Permanenter Speicher für deine Programme",
    "Verifying your code works": "Überprüfen, dass dein Code funktioniert",
    "Organizing your files": "Deine Dateien organisieren",
    "The three-phase approach": "Der Drei-Phasen-Ansatz",
    "Everything to verify before calling it done": "Alles überprüfen bevor man es fertig nennt",
    "The path from beginner to confident builder": "Der Weg vom Anfänger zum selbstbewussten Entwickler",
    "Where to go when you need help": "Wo man Hilfe findet",
    "What you've learned and where you're going": "Was du gelernt hast und wohin du gehst",
    "Everything in one page": "Alles auf einer Seite",

    # Loop diagram specifics
    "Create a function that...": "Erstelle eine Funktion, die...",
    '"Create a function that..."': '"Erstelle eine Funktion, die..."',
    "Change X to Y...": "Ändere X zu Y...",
    '"Change X to Y..."': '"Ändere X zu Y..."',
    "Fix the error...": "Behebe den Fehler...",
    '"Fix the error..."': '"Behebe den Fehler..."',
    "Typical: 2–5 cycles for simple tasks, 5–15 for complex": "Typisch: 2–5 Zyklen für einfache Aufgaben, 5–15 für komplexe",

    # Debug diagram specifics
    "Bad Debug Request": "Schlechte Debug-Anfrage",
    "Good Debug Request": "Gute Debug-Anfrage",
    "My code doesn't work, fix it": "Mein Code funktioniert nicht, reparier ihn",
    '"My code doesn\'t work, fix it"': '"Mein Code funktioniert nicht, reparier ihn"',
    "Missing: error message": "Fehlt: Fehlermeldung",
    "Missing: which line fails": "Fehlt: welche Zeile fehlschlägt",
    "Missing: relevant code": "Fehlt: relevanter Code",
    "Missing: what it should do": "Fehlt: was es tun sollte",
    "Result: AI will guess wrong": "Ergebnis: KI wird falsch raten",
    "Error: TypeError on line 15": "Fehler: TypeError in Zeile 15",
    '"Error: TypeError on line 15"': '"Fehler: TypeError in Zeile 15"',
    "Here's lines 10-20: [code]": "Hier sind Zeilen 10-20: [Code]",
    '"Here\'s lines 10-20: [code]"': '"Hier sind Zeilen 10-20: [Code]"',
    "Input was: [1, 2, None]": "Eingabe war: [1, 2, None]",
    '"Input was: [1, 2, None]"': '"Eingabe war: [1, 2, None]"',
    "Expected: sum of numbers": "Erwartet: Summe der Zahlen",
    '"Expected: sum of numbers"': '"Erwartet: Summe der Zahlen"',
    "Should skip None values": "Sollte None-Werte überspringen",
    '"Should skip None values"': '"Sollte None-Werte überspringen"',
    "Result: Precise fix provided": "Ergebnis: Präzise Lösung geliefert",

    # Common titles and headers
    "THE CORE": "DER KERN",
    "THE LOOP": "DIE SCHLEIFE",
    "THE DRAFT": "DER ENTWURF",
    "SIX OPERATIONS": "SECHS OPERATIONEN",
    "DECOMPOSITION": "ZERLEGUNG",
    "THE RULE": "DIE REGEL",
    "THE SPECTRUM": "DAS SPEKTRUM",
    "FIVE COMPONENTS": "FÜNF KOMPONENTEN",
    "GOOD VS BAD FEEDBACK": "GUTES VS SCHLECHTES FEEDBACK",
    "THE FORMULA": "DIE FORMEL",
    "THE WINDOW": "DAS FENSTER",
    "WHAT TO SHARE": "WAS TEILEN",
    "THE DECISION": "DIE ENTSCHEIDUNG",
    "THE 5-ATTEMPT RULE": "DIE 5-VERSUCH-REGEL",
    "COMMON TRAPS": "HÄUFIGE FALLEN",
    "TRUST LEVELS": "VERTRAUENSSTUFEN",
    "THE DEBUGGING FLOW": "DER DEBUGGING-ABLAUF",
    "ERROR TYPES": "FEHLERTYPEN",
    "GETTING STUCK": "FESTSTECKEN",
    "ESCAPE ROUTES": "AUSWEGE",
    "LEARNING TO READ CODE": "CODE LESEN LERNEN",
    "CODE ANATOMY": "CODE-ANATOMIE",
    "VARIABLES": "VARIABLEN",
    "CONTROL FLOW": "KONTROLLFLUSS",
    "FUNCTIONS": "FUNKTIONEN",
    "LIBRARIES": "BIBLIOTHEKEN",
    "DATA STRUCTURES": "DATENSTRUKTUREN",
    "FILES & I/O": "DATEIEN & E/A",
    "TESTING": "TESTEN",
    "PROJECT STRUCTURE": "PROJEKTSTRUKTUR",
    "YOUR FIRST PROJECT": "IHR ERSTES PROJEKT",
    "PROJECT CHECKLIST": "PROJEKT-CHECKLISTE",
    "GROWING YOUR SKILLS": "FÄHIGKEITEN ENTWICKELN",
    "RESOURCES": "RESSOURCEN",
    "THE JOURNEY": "DIE REISE",
    "KEY TAKEAWAYS": "WICHTIGSTE ERKENNTNISSE",

    # Common words and phrases
    "YOU": "DU",
    "AI": "KI",
    "Problem": "Problem",
    "Context": "Kontext",
    "Intent": "Absicht",
    "Judgment": "Urteil",
    "Code": "Code",
    "Patterns": "Muster",
    "Syntax": "Syntax",
    "Libraries": "Bibliotheken",
    "PROMPT": "PROMPT",
    "SOFTWARE": "SOFTWARE",
    "DESCRIBE": "BESCHREIBEN",
    "GET": "ERHALTEN",
    "RUN": "AUSFÜHREN",
    "EVALUATE": "BEWERTEN",
    "REFINE": "VERFEINERN",
    "DONE": "FERTIG",
    "YES": "JA",
    "NO": "NEIN",
    "CREATE": "ERSTELLEN",
    "READ": "LESEN",
    "EDIT": "BEARBEITEN",
    "FIX": "REPARIEREN",
    "EXTEND": "ERWEITERN",

    # Subtitles and descriptions
    "The fundamental partnership between human and AI": "Die fundamentale Partnerschaft zwischen Mensch und KI",
    "The fundamental rhythm of AI-assisted development": "Der fundamentale Rhythmus KI-gestützter Entwicklung",
    "What you're trying to solve": "Was du lösen willst",
    "Background AI cannot see": "Hintergrund, den KI nicht sieht",
    "What outcome you want": "Welches Ergebnis du willst",
    "Is the result correct?": "Ist das Ergebnis korrekt?",
    "Every language, every syntax": "Jede Sprache, jede Syntax",
    "Standard solutions to problems": "Standardlösungen für Probleme",
    "Exact structure code needs": "Exakte Struktur für Code",
    "Thousands of pre-built tools": "Tausende vorgefertigte Werkzeuge",
    "Your words become code": "Deine Worte werden Code",
    "Working code, delivered": "Funktionierender Code, geliefert",
    "AI generates code": "KI generiert Code",
    "Execute and observe": "Ausführen und beobachten",
    "Does it work?": "Funktioniert es?",
    "It works!": "Es funktioniert!",

    # Legend items
    "You": "Du",
    "Action": "Aktion",
    "Decision": "Entscheidung",
    "Output": "Ausgabe",
    "Prompt": "Prompt",

    # Operations
    "Make new code": "Neuen Code erstellen",
    "Explain existing code": "Bestehenden Code erklären",
    "Modify code": "Code ändern",
    "Execute yourself": "Selbst ausführen",
    "Debug errors": "Fehler debuggen",
    "Add features": "Funktionen hinzufügen",

    # Error types
    "SYNTAX": "SYNTAX",
    "RUNTIME": "LAUFZEIT",
    "LOGIC": "LOGIK",
    "Won't run": "Läuft nicht",
    "Crashes": "Stürzt ab",
    "Wrong result": "Falsches Ergebnis",

    # Common trap words
    "TRAP": "FALLE",
    "Blind Trust": "Blindes Vertrauen",
    "Vague Prompts": "Vage Prompts",
    "Too Big Tasks": "Zu große Aufgaben",
    "No Context": "Kein Kontext",
    "Giving Up Too Fast": "Zu schnell aufgeben",
    "Not Learning": "Nicht lernen",

    # Debugging flow
    "CAPTURE": "ERFASSEN",
    "LOCATE": "LOKALISIEREN",
    "CONTEXT": "KONTEXT",
    "ASK": "FRAGEN",
    "APPLY": "ANWENDEN",
    "TEST": "TESTEN",
    "Copy the exact error": "Den genauen Fehler kopieren",
    "Find the problem line": "Die Problemzeile finden",
    "Include surrounding code": "Umgebenden Code einschließen",
    "Send to AI with context": "An KI mit Kontext senden",
    "Make the fix": "Die Korrektur vornehmen",
    "Verify it's fixed": "Überprüfen, ob es behoben ist",

    # Escape routes
    "START FRESH": "NEU ANFANGEN",
    "BREAK SMALLER": "KLEINER AUFTEILEN",
    "ADD CONTEXT": "KONTEXT HINZUFÜGEN",
    "REPHRASE": "UMFORMULIEREN",
    "ASK WHY": "NACH DEM WARUM FRAGEN",
    "SIMPLIFY": "VEREINFACHEN",

    # Project related
    "PLAN": "PLANEN",
    "BUILD": "BAUEN",
    "POLISH": "VERFEINERN",
    "Before Starting": "Vor dem Start",
    "While Building": "Während des Bauens",
    "Before Finishing": "Vor dem Abschluss",
    "Quality Check": "Qualitätsprüfung",
    "Final Questions": "Letzte Fragen",

    # Skills progression
    "BEGINNER": "ANFÄNGER",
    "COMPETENT": "KOMPETENT",
    "CONFIDENT": "SELBSTSICHER",
    "Stage 1: Copy": "Phase 1: Kopieren",
    "Stage 2: Modify": "Phase 2: Modifizieren",
    "Stage 3: Create": "Phase 3: Erschaffen",

    # Resources
    "AI Tools": "KI-Werkzeuge",
    "Learning More": "Weiterlernen",
    "Practice Ideas": "Übungsideen",

    # Journey
    "You Started Here": "Du hast hier angefangen",
    "What You Learned": "Was du gelernt hast",
    "You Are Here": "Du bist hier",
    "Skills You Now Have": "Fähigkeiten, die du jetzt hast",
    "What's Next": "Was kommt als Nächstes",

    # Misc phrases
    "Better information in = Better fix out": "Bessere Information rein = Bessere Lösung raus",
    "Every problem has an escape route": "Jedes Problem hat einen Ausweg",
    "The Pattern": "Das Muster",
    "The Secret": "Das Geheimnis",
    "The Truth About Coding": "Die Wahrheit über Programmieren",

    # Six Operations diagram - additional translations
    "Every AI interaction falls into one of these categories": "Jede KI-Interaktion fällt in eine dieser Kategorien",
    "Every prompt you write is one of these six operations": "Jeder Prompt, den du schreibst, ist eine dieser sechs Operationen",
    "Create a file that does X": "Erstelle eine Datei, die X macht",
    '"Create a file that does X"': '"Erstelle eine Datei, die X macht"',
    "Explain what this code does": "Erkläre, was dieser Code macht",
    '"Explain what this code does"': '"Erkläre, was dieser Code macht"',
    "Change the timeout to 30s": "Ändere den Timeout auf 30s",
    '"Change the timeout to 30s"': '"Ändere den Timeout auf 30s"',
    "Run the server": "Server starten",
    '"Run the server"': '"Server starten"',
    "TypeError: undefined. Fix this.": "TypeError: undefined. Behebe das.",
    '"TypeError: undefined. Fix this."': '"TypeError: undefined. Behebe das."',
    "Add logging to this function": "Füge Logging zu dieser Funktion hinzu",
    '"Add logging to this function"': '"Füge Logging zu dieser Funktion hinzu"',
    "Start from nothing": "Von Null anfangen",
    "Learn existing code": "Bestehenden Code verstehen",
    "Modify existing": "Bestehendes ändern",
    "Execute code": "Code ausführen",
    "Resolve errors": "Fehler beheben",
    "File": "Datei",
    "File +": "Datei +",
    "Change": "Änderung",
    "Command": "Befehl",
    "Exec": "Ausf.",
    "Error": "Fehler",
    "Fixed": "Behoben",
    "Understand": "Verstehen",
    "Updated": "Aktualisiert",
    "Enhanced": "Erweitert",
    "Existing +": "Bestehendes +",
    "Request": "Anfrage",
    "Input (You provide)": "Eingabe (Du lieferst)",
    "AI Processing": "KI-Verarbeitung",
    "Output (You get)": "Ausgabe (Du bekommst)",

    # Common traps diagram - additional translations
    "TRAP 1": "FALLE 1",
    "TRAP 2": "FALLE 2",
    "TRAP 3": "FALLE 3",
    "TRAP 4": "FALLE 4",
    "TRAP 5": "FALLE 5",
    "TRAP 6": "FALLE 6",
    "Running code without reading it": "Code ausführen ohne ihn zu lesen",
    "Fix: Always review before running": "Lösung: Immer prüfen vor dem Ausführen",
    "Ask AI to explain what it does": "KI bitten zu erklären, was es macht",
    '"Make it better" or "Fix this"': '"Mach es besser" oder "Reparier das"',
    "Fix: Be specific about what's wrong": "Lösung: Sei spezifisch, was falsch ist",
    "State expected vs actual behavior": "Erwartetes vs. tatsächliches Verhalten angeben",
    '"Build me a whole app"': '"Baue mir eine ganze App"',
    "Fix: Break into small tasks": "Lösung: In kleine Aufgaben aufteilen",
    "One feature at a time": "Eine Funktion nach der anderen",
    "Not sharing error messages or code": "Keine Fehlermeldungen oder Code teilen",
    "Fix: Paste errors and code": "Lösung: Fehler und Code einfügen",
    "Include relevant files": "Relevante Dateien einschließen",
    "First attempt didn't work, quit": "Erster Versuch hat nicht funktioniert, aufgeben",
    "Fix: Iterate and refine": "Lösung: Iterieren und verfeinern",
    "Give 3-5 attempts": "3-5 Versuche geben",
    "Copy-paste without understanding": "Kopieren ohne zu verstehen",
    "Fix: Ask AI to explain": "Lösung: KI bitten zu erklären",
    "Learn from each solution": "Von jeder Lösung lernen",
    "Most traps come from treating AI like magic instead of a tool": "Die meisten Fallen entstehen, wenn KI wie Magie statt als Werkzeug behandelt wird",
    "Stay engaged, stay specific, stay curious": "Bleib engagiert, bleib spezifisch, bleib neugierig",
    "Awareness of traps = Avoidance of traps": "Bewusstsein für Fallen = Vermeidung von Fallen",

    # Debugging flow - step numbers
    "1. CAPTURE": "1. ERFASSEN",
    "2. LOCATE": "2. LOKALISIEREN",
    "3. CONTEXT": "3. KONTEXT",
    "4. ASK": "4. FRAGEN",
    "5. APPLY": "5. ANWENDEN",
    "6. TEST": "6. TESTEN",

    # Decomposition diagram
    "Break big tasks into AI-sized pieces": "Große Aufgaben in KI-gerechte Teile zerlegen",
    "Build a bolt calculator app": "Eine Schraubenrechner-App erstellen",
    "TOO BIG for one prompt": "ZU GROSS für einen Prompt",
    "Input Module": "Eingabe-Modul",
    "Calculation Module": "Berechnungs-Modul",
    "Output Module": "Ausgabe-Modul",
    "Still needs breakdown": "Muss noch aufgeteilt werden",
    "Bolt diameter": "Schraubendurchmesser",
    "Material grade": "Materialklasse",
    "Load value": "Lastwert",
    "Stress formula": "Spannungsformel",
    "Safety factor": "Sicherheitsfaktor",
    "Unit conversion": "Einheitenumrechnung",
    "Result display": "Ergebnisanzeige",
    "Pass/fail check": "Bestanden/Fehler-Prüfung",
    "Report format": "Berichtformat",
    "The Goal": "Das Ziel",
    "The Test": "Der Test",
    "Each piece should be small enough": "Jedes Teil sollte klein genug sein",
    "to describe in ONE sentence": "um es in EINEM Satz zu beschreiben",
    '"Can I explain this task in one sentence?"': '"Kann ich diese Aufgabe in einem Satz erklären?"',
    "No → Break it down further": "Nein → Weiter aufteilen",
    "Big problems → Small prompts → Working code": "Große Probleme → Kleine Prompts → Funktionierender Code",

    # Spectrum diagram
    "More specific prompts get better results": "Spezifischere Prompts liefern bessere Ergebnisse",
    "VAGUE": "VAGE",
    "MODERATE": "MITTEL",
    "PRECISE": "PRÄZISE",
    '"Make it better"': '"Mach es besser"',
    "AI thinks:": "KI denkt:",
    "Better how? Faster? Cleaner?": "Besser wie? Schneller? Sauberer?",
    "More features? Different style?": "Mehr Funktionen? Anderer Stil?",
    "Result:": "Ergebnis:",
    "Random changes, likely wrong": "Zufällige Änderungen, wahrscheinlich falsch",
    '"Make it faster"': '"Mach es schneller"',
    "Speed is the goal. But which part?": "Geschwindigkeit ist das Ziel. Aber welcher Teil?",
    "How much faster?": "Wie viel schneller?",
    "Might work, might miss the point": "Könnte funktionieren, könnte das Ziel verfehlen",
    '"Cache the API response for': '"Cache die API-Antwort für',
    '5 minutes to reduce load time"': '5 Minuten um die Ladezeit zu reduzieren"',
    "Add caching. 5 min expiry.": "Caching hinzufügen. 5 Min Ablauf.",
    "Target: API response. Goal: speed.": "Ziel: API-Antwort. Zweck: Geschwindigkeit.",
    "✓ Exactly what you wanted": "✓ Genau das, was du wolltest",
    "Success rate:": "Erfolgsrate:",
    "Specificity Formula:": "Spezifitäts-Formel:",
    "WHAT + WHERE + HOW + WHY = Clear Result": "WAS + WO + WIE + WARUM = Klares Ergebnis",
    "If AI guesses wrong, your prompt was too vague": "Wenn KI falsch rät, war dein Prompt zu vage",

    # Common words in diagrams
    "Prompt:": "Prompt:",

    # Stuck diagram
    "Warning Signs": "Warnzeichen",
    "You might be stuck if...": "Du steckst vielleicht fest, wenn...",
    "Same error keeps coming back": "Der gleiche Fehler kommt immer wieder",
    "Fixing one thing breaks another": "Eine Sache reparieren bricht eine andere",
    "AI gives same answer repeatedly": "KI gibt wiederholt die gleiche Antwort",
    "More than 5 attempts, no progress": "Mehr als 5 Versuche, kein Fortschritt",
    "Getting frustrated or confused": "Frustriert oder verwirrt werden",
    "What's Happening": "Was passiert",
    "Common causes of getting stuck": "Häufige Gründe fürs Feststecken",
    "Wrong mental model of the problem": "Falsches mentales Modell des Problems",
    "Missing crucial information": "Wichtige Informationen fehlen",
    "Task is actually too complex": "Aufgabe ist tatsächlich zu komplex",
    "Solving wrong problem entirely": "Das falsche Problem wird gelöst",
    "Context window exhausted": "Kontextfenster erschöpft",
    "The Stuck Loop": "Die Feststeck-Schleife",
    "TRY": "VERSUCH",
    "FAIL": "FEHLER",
    "TRY AGAIN": "ERNEUT VERSUCHEN",
    "SAME FAIL": "GLEICHER FEHLER",
    "Being stuck is information: your approach needs to change": "Feststecken ist Information: dein Ansatz muss sich ändern",
    "Recognize stuck early = Save time and frustration": "Feststecken früh erkennen = Zeit und Frust sparen",

    # Learning to read code diagram
    "You don't need to write code to understand it": "Du musst keinen Code schreiben, um ihn zu verstehen",
    "Reading code is like reading a recipe - you can follow along": "Code lesen ist wie ein Rezept lesen - du kannst folgen",
    "without being a chef": "ohne Koch zu sein",
    "LOOK FOR": "ACHTE AUF",
    "Patterns you can recognize": "Muster, die du erkennen kannst",
    "Names": "Namen",
    "Variables describe what they hold": "Variablen beschreiben, was sie enthalten",
    "Structure": "Struktur",
    "Indentation shows grouping": "Einrückung zeigt Gruppierung",
    "Keywords": "Schlüsselwörter",
    "if, for, while, return": "if, for, while, return",
    "Comments": "Kommentare",
    "Human explanations in code": "Menschliche Erklärungen im Code",
    "Flow": "Ablauf",
    "Top to bottom, branching": "Von oben nach unten, Verzweigungen",
    "ASK AI": "FRAGE KI",
    "Questions to understand code": "Fragen zum Code-Verständnis",
    '"What does this code do?"': '"Was macht dieser Code?"',
    '"Explain line by line"': '"Erkläre Zeile für Zeile"',
    '"What is [variable] for?"': '"Wofür ist [Variable]?"',
    '"Why is this needed?"': '"Warum ist das nötig?"',
    '"What would break this?"': '"Was würde das kaputt machen?"',
    '"Simplify this for me"': '"Vereinfache das für mich"',
    "AI is your code interpreter!": "KI ist dein Code-Dolmetscher!",
    "SKIP FOR NOW": "ERSTMAL ÜBERSPRINGEN",
    "Don't worry about these yet": "Mach dir darüber noch keine Sorgen",
    "Memorizing syntax": "Syntax auswendig lernen",
    "Understanding every detail": "Jedes Detail verstehen",
    "Advanced patterns": "Fortgeschrittene Muster",
    "Optimization tricks": "Optimierungstricks",
    "Framework internals": "Framework-Interna",
    "Focus on the big picture first": "Konzentriere dich zuerst aufs große Ganze",
    "Goal: Understand what code does, not memorize how to write it": "Ziel: Verstehen, was Code macht, nicht wie man ihn schreibt",
    "Reading + AI explanations = Understanding": "Lesen + KI-Erklärungen = Verständnis",

    # Journey diagram
    '"I can\'t code"': '"Ich kann nicht programmieren"',
    '"I build with AI"': '"Ich baue mit KI"',
    "The Loop: Describe → Get → Run → Evaluate": "Die Schleife: Beschreiben → Erhalten → Ausführen → Bewerten",
    "Decomposition: Big tasks → Small tasks": "Zerlegung: Große Aufgaben → Kleine Aufgaben",
    "Communication: Specific prompts → Better results": "Kommunikation: Spezifische Prompts → Bessere Ergebnisse",
    "Read and understand code": "Code lesen und verstehen",
    "Communicate with AI effectively": "Effektiv mit KI kommunizieren",
    "Debug and fix problems": "Probleme debuggen und beheben",
    "Build working solutions": "Funktionierende Lösungen bauen",
    "Pick a real problem you want to solve": "Wähle ein echtes Problem, das du lösen willst",
    "Build your first real project": "Baue dein erstes echtes Projekt",
    "Share it with someone": "Teile es mit jemandem",
    "Then build another one!": "Dann baue noch eines!",
    "You don't need to know everything to build something useful": "Du musst nicht alles wissen, um etwas Nützliches zu bauen",
    "Everyone looks things up. Everyone gets stuck. Everyone asks for help.": "Jeder schaut Dinge nach. Jeder steckt fest. Jeder fragt um Hilfe.",
    "The only difference is persistence.": "Der einzige Unterschied ist Ausdauer.",
    "Now go build something!": "Jetzt geh und baue etwas!",

    # Variables diagram
    "Variables are like labeled boxes - the name tells you what's inside": "Variablen sind wie beschriftete Kisten - der Name sagt dir, was drin ist",
    "The Concept": "Das Konzept",
    "The Code": "Der Code",
    "The Meaning": "Die Bedeutung",
    "name = value": "name = wert",
    '"Store 12.5 in a box': '"Speichere 12.5 in einer Kiste',
    'labeled bolt_diameter"': 'mit der Beschriftung bolt_diameter"',
    "NUMBERS": "ZAHLEN",
    "TEXT": "TEXT",
    "TRUE/FALSE": "WAHR/FALSCH",
    "LISTS": "LISTEN",
    "Multiple items": "Mehrere Elemente",
    "Naming rules: No spaces (use_underscores), start with letter, be descriptive": "Namensregeln: Keine Leerzeichen (benutze_unterstriche), mit Buchstabe beginnen, beschreibend sein",
    "Good: bolt_count, max_stress    Bad: x, bc, thing1": "Gut: bolt_count, max_stress    Schlecht: x, bc, thing1",
    "Good variable names make code self-documenting": "Gute Variablennamen machen Code selbsterklärend",

    # Control flow diagram
    "How programs make decisions and repeat": "Wie Programme Entscheidungen treffen und wiederholen",
    "IF/ELSE": "WENN/SONST",
    "Making decisions": "Entscheidungen treffen",
    "LOOPS": "SCHLEIFEN",
    "Repeating actions": "Aktionen wiederholen",
    "The building blocks of logic": "Die Bausteine der Logik",
    "condition": "bedingung",
    "do this": "mach das",
    "do that": "mach jenes",
    "for each": "für jedes",
    "in list": "in liste",
    "while": "solange",
    "is true": "wahr ist",
    "Condition check": "Bedingungsprüfung",
    "One path": "Ein Pfad",
    "Other path": "Anderer Pfad",
    "Repeat for each item": "Für jedes Element wiederholen",
    "Repeat while condition true": "Wiederholen solange Bedingung wahr",
    "Programs are just decisions and repetitions": "Programme sind nur Entscheidungen und Wiederholungen",

    # Functions diagram
    "Reusable blocks of code": "Wiederverwendbare Code-Blöcke",
    "Think of functions as mini-programs you can call by name": "Denk an Funktionen als Mini-Programme, die du per Namen aufrufen kannst",
    "ANATOMY": "ANATOMIE",
    "Parts of a function": "Teile einer Funktion",
    "Name": "Name",
    "Inputs": "Eingaben",
    "Output": "Ausgabe",
    "EXAMPLE": "BEISPIEL",
    "Real function": "Echte Funktion",
    "USAGE": "VERWENDUNG",
    "Calling a function": "Funktion aufrufen",
    "Call the function": "Funktion aufrufen",
    "Pass in values": "Werte übergeben",
    "Get result back": "Ergebnis zurückbekommen",
    "Functions = Reuse code without copying": "Funktionen = Code wiederverwenden ohne kopieren",

    # Libraries diagram
    "Standing on the shoulders of giants": "Auf den Schultern von Riesen stehen",
    "Libraries are pre-written code you can use - don't reinvent the wheel": "Bibliotheken sind vorgefertigter Code - erfinde das Rad nicht neu",
    "WHAT THEY ARE": "WAS SIE SIND",
    "Collections of functions": "Sammlungen von Funktionen",
    "HOW TO USE": "WIE MAN SIE BENUTZT",
    "Import and call": "Importieren und aufrufen",
    "COMMON TYPES": "HÄUFIGE TYPEN",
    "Math": "Mathematik",
    "Files": "Dateien",
    "Web": "Web",
    "Data": "Daten",
    "Pre-built tools": "Vorgefertigte Werkzeuge",
    "for common tasks": "für häufige Aufgaben",
    "Step 1: Import": "Schritt 1: Importieren",
    "Step 2: Use": "Schritt 2: Benutzen",
    "Ask AI: 'What library for [task]?'": "Frag KI: 'Welche Bibliothek für [Aufgabe]?'",

    # Data structures diagram
    "How to organize your data": "Wie du deine Daten organisierst",
    "Different structures for different needs": "Verschiedene Strukturen für verschiedene Bedürfnisse",
    "LIST": "LISTE",
    "Ordered collection": "Geordnete Sammlung",
    "DICTIONARY": "WÖRTERBUCH",
    "Key-value pairs": "Schlüssel-Wert-Paare",
    "Use for: Sequences, collections": "Verwenden für: Sequenzen, Sammlungen",
    "Use for: Lookups, properties": "Verwenden für: Abfragen, Eigenschaften",
    "Access by position": "Zugriff über Position",
    "Access by name": "Zugriff über Name",
    "Choose structure based on how you'll access data": "Wähle Struktur basierend auf wie du auf Daten zugreifen wirst",

    # Files & I/O diagram
    "Permanent storage for your programs": "Permanenter Speicher für deine Programme",
    "Programs can read and write files to save data between runs": "Programme können Dateien lesen und schreiben um Daten zwischen Läufen zu speichern",
    "READING": "LESEN",
    "Getting data from files": "Daten aus Dateien holen",
    "WRITING": "SCHREIBEN",
    "Saving data to files": "Daten in Dateien speichern",
    "COMMON FORMATS": "HÄUFIGE FORMATE",
    "Plain text": "Klartext",
    "Structured data": "Strukturierte Daten",
    "Spreadsheets": "Tabellen",
    "Open file": "Datei öffnen",
    "Read content": "Inhalt lesen",
    "Close file": "Datei schließen",
    "Create/open": "Erstellen/öffnen",
    "Write content": "Inhalt schreiben",
    "Always close files or use 'with' statement": "Immer Dateien schließen oder 'with'-Anweisung benutzen",

    # Testing diagram
    "Verifying your code works": "Überprüfen, dass dein Code funktioniert",
    "Tests check that code does what you expect": "Tests prüfen, ob Code tut, was du erwartest",
    "WHY TEST": "WARUM TESTEN",
    "Catch bugs early": "Fehler früh finden",
    "HOW TO TEST": "WIE MAN TESTET",
    "Compare expected vs actual": "Erwartetes vs tatsächliches vergleichen",
    "WHAT TO TEST": "WAS TESTEN",
    "Normal cases": "Normale Fälle",
    "Edge cases": "Grenzfälle",
    "Error cases": "Fehlerfälle",
    "Confidence to change code": "Vertrauen, Code zu ändern",
    "Documentation of behavior": "Dokumentation des Verhaltens",
    "Input → Function → Output": "Eingabe → Funktion → Ausgabe",
    "Expected === Actual?": "Erwartet === Tatsächlich?",
    "Test early, test often, test edge cases": "Früh testen, oft testen, Grenzfälle testen",

    # Project structure diagram
    "Organizing your files": "Deine Dateien organisieren",
    "A consistent structure makes projects manageable": "Eine konsistente Struktur macht Projekte handhabbar",
    "TYPICAL LAYOUT": "TYPISCHES LAYOUT",
    "PROJECT/": "PROJEKT/",
    "Your code": "Dein Code",
    "Dependencies": "Abhängigkeiten",
    "Configuration": "Konfiguration",
    "Documentation": "Dokumentation",
    "KEY PRINCIPLES": "SCHLÜSSELPRINZIPIEN",
    "Group related files": "Verwandte Dateien gruppieren",
    "Descriptive names": "Beschreibende Namen",
    "Separate concerns": "Zuständigkeiten trennen",
    "Keep it simple": "Einfach halten",
    "Start simple, organize as you grow": "Einfach anfangen, beim Wachsen organisieren",

    # First project diagram
    "The three-phase approach": "Der Drei-Phasen-Ansatz",
    "Start small, prove it works, then expand": "Klein anfangen, beweisen dass es funktioniert, dann erweitern",
    "1. MINIMUM": "1. MINIMUM",
    "Get something working": "Etwas zum Laufen bringen",
    "2. ITERATE": "2. ITERIEREN",
    "Add one feature at a time": "Eine Funktion nach der anderen hinzufügen",
    "3. COMPLETE": "3. FERTIGSTELLEN",
    "Polish and finish": "Polieren und fertigstellen",
    "Simplest possible version": "Einfachste mögliche Version",
    "Does the core thing work?": "Funktioniert die Kernfunktion?",
    "Test after each addition": "Nach jeder Hinzufügung testen",
    "Keep the code working": "Code am Laufen halten",
    "Clean up": "Aufräumen",
    "Add error handling": "Fehlerbehandlung hinzufügen",
    "Document": "Dokumentieren",
    "Working > Perfect. Ship small, improve later.": "Funktionierend > Perfekt. Klein ausliefern, später verbessern.",

    # Project checklist diagram
    "Everything to verify before calling it done": "Alles überprüfen bevor man es fertig nennt",
    "Does it work?": "Funktioniert es?",
    "Runs without errors": "Läuft ohne Fehler",
    "Gives correct output": "Gibt korrektes Ergebnis",
    "Handles bad input": "Verarbeitet schlechte Eingaben",
    "Is it usable?": "Ist es benutzbar?",
    "Clear instructions": "Klare Anleitungen",
    "Meaningful errors": "Aussagekräftige Fehler",
    "Easy to run": "Einfach auszuführen",
    "Is it maintainable?": "Ist es wartbar?",
    "Readable code": "Lesbarer Code",
    "Commented logic": "Kommentierte Logik",
    "Organized files": "Organisierte Dateien",
    "Done is better than perfect": "Fertig ist besser als perfekt",

    # Growing skills diagram
    "The path from beginner to confident builder": "Der Weg vom Anfänger zum selbstbewussten Entwickler",
    "Copy existing code": "Bestehenden Code kopieren",
    "Follow tutorials": "Tutorials folgen",
    "Ask AI everything": "KI alles fragen",
    "Modify copied code": "Kopierten Code anpassen",
    "Combine examples": "Beispiele kombinieren",
    "Understand patterns": "Muster verstehen",
    "Start from scratch": "Von Null anfangen",
    "Debug independently": "Selbstständig debuggen",
    "Teach others": "Anderen beibringen",
    "Each project teaches something new": "Jedes Projekt lehrt etwas Neues",

    # Resources diagram
    "Where to go when you need help": "Wo du Hilfe findest",
    "ChatGPT, Claude": "ChatGPT, Claude",
    "First stop for help": "Erste Anlaufstelle",
    "YouTube, Courses": "YouTube, Kurse",
    "Learn concepts": "Konzepte lernen",
    "Stack Overflow": "Stack Overflow",
    "Common problems": "Häufige Probleme",
    "Documentation": "Dokumentation",
    "Official reference": "Offizielle Referenz",
    "Ask AI first, it knows your context": "Frag zuerst KI, sie kennt deinen Kontext",

    # First project diagram - remaining phrases
    "Applying everything you've learned": "Alles anwenden, was du gelernt hast",
    "Start small, make it work, then expand": "Klein anfangen, zum Laufen bringen, dann erweitern",
    "1. PLAN": "1. PLANEN",
    "2. BUILD": "2. BAUEN",
    "3. REFINE": "3. VERFEINERN",
    "Define your goal": "Definiere dein Ziel",
    "What should it do?": "Was soll es tun?",
    "What inputs/outputs?": "Welche Ein-/Ausgaben?",
    "What's the simplest version?": "Was ist die einfachste Version?",
    "Write it in one sentence": "Schreib es in einem Satz",
    "before coding": "vor dem Programmieren",
    "Work with AI": "Mit KI arbeiten",
    "Start with core feature": "Mit Kernfunktion beginnen",
    "Test as you go": "Testen während du arbeitest",
    "Add features one by one": "Funktionen einzeln hinzufügen",
    "Get it working before": "Zum Laufen bringen bevor",
    "making it perfect": "es perfekt machen",
    "Polish it": "Verfeinern",
    "Handle edge cases": "Grenzfälle behandeln",
    "Add error messages": "Fehlermeldungen hinzufügen",
    "Clean up code": "Code aufräumen",
    "Ask AI to review": "KI um Überprüfung bitten",
    "and improve": "und verbessern",
    "Example First Project: Bolt Stress Calculator": "Beispiel Erstes Projekt: Schraubenspannungs-Rechner",
    "Plan:": "Plan:",
    "Build:": "Bauen:",
    "Refine:": "Verfeinern:",
    '"Calculate stress from force and area, warn if too high"': '"Spannung aus Kraft und Fläche berechnen, warnen wenn zu hoch"',
    "1. Create function  2. Add input  3. Add warning  4. Format output": "1. Funktion erstellen  2. Eingabe hinzufügen  3. Warnung hinzufügen  4. Ausgabe formatieren",
    "Handle zero area, add units, save to file": "Null-Fläche behandeln, Einheiten hinzufügen, in Datei speichern",
    "Done is better than perfect - ship V1, improve later": "Fertig ist besser als perfekt - V1 ausliefern, später verbessern",

    # Summary/Key takeaways diagram
    "What you've learned and where you're going": "Was du gelernt hast und wohin du gehst",
    "Everything in one page": "Alles auf einer Seite",

    # Cheat sheet - Header
    "FROM NON-CODER TO BUILDER": "VOM NICHT-PROGRAMMIERER ZUM BUILDER",
    "Quick Reference Cheat Sheet": "Kurzreferenz-Spickzettel",

    # Cheat sheet - Core partnership
    "YOU + AI = BUILDER  |  You: Direction &amp; Judgment  |  AI: Code &amp; Speed": "DU + KI = BUILDER  |  Du: Richtung &amp; Urteil  |  KI: Code &amp; Tempo",

    # Cheat sheet - Loop section
    "DESCRIBE → GET → RUN → EVALUATE": "BESCHREIBEN → ERHALTEN → AUSFÜHREN → BEWERTEN",
    "1. Describe what you want in plain English": "1. Beschreibe, was du willst, in einfachen Worten",
    "2. Get code from AI (don't worry if you don't understand)": "2. Erhalte Code von KI (keine Sorge, wenn du es nicht verstehst)",
    "3. Run it → 4. Evaluate results → Repeat until it works": "3. Führe es aus → 4. Bewerte Ergebnisse → Wiederhole bis es funktioniert",

    # Cheat sheet - Decomposition section
    "BIG TASK → SMALL TASKS": "GROSSE AUFGABE → KLEINE AUFGABEN",
    "Rule: If it takes more than one sentence, split it": "Regel: Wenn es mehr als einen Satz braucht, teile es auf",
    "Each piece should be testable independently": "Jedes Teil sollte unabhängig testbar sein",
    "Build one piece at a time, verify, then continue": "Baue ein Teil nach dem anderen, überprüfe, dann weiter",

    # Cheat sheet - Effective Prompts
    "EFFECTIVE PROMPTS": "EFFEKTIVE PROMPTS",
    'Bad: "Make it work"': 'Schlecht: "Mach es fertig"',
    "Good: Include these 5 elements:": "Gut: Diese 5 Elemente einschließen:",
    '• WHAT: "Create a function that calculates..."': '• WAS: "Erstelle eine Funktion, die berechnet..."',
    '• WHERE: "In Python, add to the existing file..."': '• WO: "In Python, zur bestehenden Datei hinzufügen..."',
    '• HOW: "Use the formula: stress = force / area"': '• WIE: "Benutze die Formel: Spannung = Kraft / Fläche"',
    '• WHY: "This will be used for safety checks"': '• WARUM: "Das wird für Sicherheitsprüfungen verwendet"',

    # Cheat sheet - Feedback section
    "GIVING FEEDBACK": "FEEDBACK GEBEN",
    "GOT X, EXPECTED Y, CHANGE Z": "ERHALTEN X, ERWARTET Y, ÄNDERE Z",
    '• "I got [actual result]"': '• "Ich habe [tatsächliches Ergebnis] bekommen"',
    '• "I expected [what you wanted]"': '• "Ich habe [was du wolltest] erwartet"',
    '• "Please change [specific thing]"': '• "Bitte ändere [spezifische Sache]"',
    "Include error messages, screenshots, examples": "Fehlermeldungen, Screenshots, Beispiele einschließen",

    # Cheat sheet - Debugging section
    "DEBUGGING ERRORS": "FEHLER DEBUGGEN",
    "Syntax Error:": "Syntaxfehler:",
    "Typo - check spelling, brackets, colons": "Tippfehler - prüfe Rechtschreibung, Klammern, Doppelpunkte",
    "Name Error:": "Namensfehler:",
    "Variable doesn't exist - check spelling": "Variable existiert nicht - prüfe Rechtschreibung",
    "Type Error:": "Typfehler:",
    "Wrong data type - string vs number": "Falscher Datentyp - String vs Zahl",
    "Index Error:": "Indexfehler:",
    "List position doesn't exist": "Listenposition existiert nicht",
    "Copy full error message → Paste to AI → Ask for fix": "Komplette Fehlermeldung kopieren → An KI einfügen → Nach Lösung fragen",

    # Cheat sheet - 5-Attempt Rule
    "STUCK AFTER 5 TRIES? RESTART FRESH": "NACH 5 VERSUCHEN FESTSTECKEN? NEU ANFANGEN",
    "1. Start new conversation (clear context)": "1. Neue Konversation starten (Kontext löschen)",
    "2. Rephrase the problem differently": "2. Das Problem anders formulieren",
    "3. Break into smaller pieces": "3. In kleinere Teile aufteilen",
    "Sunk cost fallacy is real - cut losses early": "Versunkene Kosten sind real - Verluste früh begrenzen",

    # Cheat sheet - Reading Code
    "READING CODE": "CODE LESEN",
    "Variables:": "Variablen:",
    "Named boxes storing values (x = 5)": "Benannte Kisten, die Werte speichern (x = 5)",
    "Functions:": "Funktionen:",
    "Reusable recipes (def calculate():)": "Wiederverwendbare Rezepte (def calculate():)",
    "Conditionals:": "Bedingungen:",
    "Decisions (if/else)": "Entscheidungen (if/else)",
    "Loops:": "Schleifen:",
    "Repeat actions (for, while)": "Aktionen wiederholen (for, while)",
    "Lists:": "Listen:",
    "Collections ([1, 2, 3]) - Dicts: key-value pairs": "Sammlungen ([1, 2, 3]) - Dicts: Schlüssel-Wert-Paare",

    # Cheat sheet - Sharing Context
    "SHARING CONTEXT": "KONTEXT TEILEN",
    "AI ONLY KNOWS WHAT YOU TELL IT": "KI WEISS NUR, WAS DU IHR SAGST",
    "Always include:": "Immer einschließen:",
    "• Your existing code (paste it)": "• Dein bestehender Code (einfügen)",
    "• Full error messages (copy exactly)": "• Vollständige Fehlermeldungen (exakt kopieren)",
    "• What you've already tried": "• Was du bereits versucht hast",

    # Cheat sheet - Trust Levels
    "AI TRUST LEVELS": "KI-VERTRAUENSSTUFEN",
    "High trust:": "Hohes Vertrauen:",
    "Syntax, boilerplate": "Syntax, Standardcode",
    "Medium:": "Mittel:",
    "Logic, algorithms": "Logik, Algorithmen",
    "Verify:": "Überprüfen:",
    "Business logic, edge cases": "Geschäftslogik, Grenzfälle",
    "Always test:": "Immer testen:",
    "Security, data": "Sicherheit, Daten",

    # Cheat sheet - When Stuck
    "WHEN STUCK": "WENN FESTSTECKEN",
    "1. Ask AI with full context": "1. KI mit vollem Kontext fragen",
    "2. Search the error online": "2. Fehler online suchen",
    "3. Rephrase the question": "3. Die Frage umformulieren",
    "4. Break into smaller parts": "4. In kleinere Teile aufteilen",

    # Cheat sheet - Formula
    "Clear Goal + Small Steps + Iteration + Persistence = Working Code": "Klares Ziel + Kleine Schritte + Iteration + Ausdauer = Funktionierender Code",

    # Cheat sheet - Quick Commands
    "QUICK PYTHON COMMANDS": "SCHNELLE PYTHON-BEFEHLE",

    # Cheat sheet - Magic Phrases
    "MAGIC PHRASES FOR AI": "ZAUBERSPRÜCHE FÜR KI",
    '"Explain like I\'m new"': '"Erkläre es mir als Anfänger"',
    '"What does this error mean?"': '"Was bedeutet dieser Fehler?"',
    '"Show me step by step"': '"Zeig mir Schritt für Schritt"',
    '"What am I missing?"': '"Was fehlt mir?"',

    # Cheat sheet - Footer
    "You don't need to know everything to build something useful. Start building!": "Du musst nicht alles wissen, um etwas Nützliches zu bauen. Fang an zu bauen!",

    # 06-good-vs-bad.svg - Feedback diagram
    "BAD FEEDBACK": "SCHLECHTES FEEDBACK",
    "GOOD FEEDBACK": "GUTES FEEDBACK",
    '✗ "It doesn\'t work"': '✗ "Es funktioniert nicht"',
    "AI has no idea what's wrong": "KI hat keine Ahnung, was falsch ist",
    '✗ "This is wrong"': '✗ "Das ist falsch"',
    "Wrong how? What did you expect?": "Falsch wie? Was hast du erwartet?",
    '✗ "Fix it"': '✗ "Reparier es"',
    "Fix what? AI will guess (usually wrong)": "Was reparieren? KI wird raten (meist falsch)",
    '✗ "That\'s not what I wanted"': '✗ "Das ist nicht, was ich wollte"',
    "Then what DID you want?": "Was wolltest du denn?",
    "Result: More cycles, more frustration": "Ergebnis: Mehr Zyklen, mehr Frust",
    '✓ "Getting error: TypeError on line 15"': '✓ "Bekomme Fehler: TypeError in Zeile 15"',
    "AI knows exactly where to look": "KI weiß genau, wo sie suchen muss",
    '✓ "Output is 5, but should be 10"': '✓ "Ausgabe ist 5, sollte aber 10 sein"',
    "AI knows the gap to close": "KI kennt die Lücke zu schließen",
    '✓ "Change the loop to start at 1, not 0"': '✓ "Ändere die Schleife, bei 1 starten, nicht 0"',
    "AI knows exactly what to change": "KI weiß genau, was zu ändern ist",
    '✓ "Add validation: reject negative numbers"': '✓ "Validierung hinzufügen: negative Zahlen ablehnen"',
    "AI knows the requirement": "KI kennt die Anforderung",
    "Result: Fast fixes, working code": "Ergebnis: Schnelle Lösungen, funktionierender Code",
    "Specific feedback → Specific fixes → Done faster": "Spezifisches Feedback → Spezifische Lösungen → Schneller fertig",

    # 14-1-functions.svg
    "Reusable machines that do one job": "Wiederverwendbare Maschinen für eine Aufgabe",
    "A function is like a machine: put something in, get something out": "Eine Funktion ist wie eine Maschine: etwas rein, etwas raus",
    "The Machine": "Die Maschine",
    "Der Code": "Der Code",
    "INPUT": "EINGABE",
    "OUTPUT": "AUSGABE",
    "Call it anywhere, reuse forever": "Überall aufrufen, für immer wiederverwenden",
    "Why Use Functions?": "Warum Funktionen nutzen?",
    "Reuse code (write once)": "Code wiederverwenden (einmal schreiben)",
    "Organize logic (clear names)": "Logik organisieren (klare Namen)",
    "Test easily (isolated units)": "Einfach testen (isolierte Einheiten)",
    "Fix in one place": "An einer Stelle reparieren",
    "Function Parts": "Funktionsteile",
    "Name (what it does)": "Name (was sie tut)",
    "Parameters (inputs)": "Parameter (Eingaben)",
    "Body (the work)": "Körper (die Arbeit)",
    "Return (output)": "Rückgabe (Ausgabe)",
    "Ask AI To...": "Frag KI nach...",
    '"Erstelle eine Funktion, die..."': '"Erstelle eine Funktion, die..."',
    '"Explain this function"': '"Erkläre diese Funktion"',
    '"What does it return?"': '"Was gibt sie zurück?"',
    '"Add error handling"': '"Füge Fehlerbehandlung hinzu"',
    "Functions = Reusable building blocks of code": "Funktionen = Wiederverwendbare Code-Bausteine",

    # 14-2-libraries.svg
    "Pre-built code you can use": "Vorgefertigter Code zum Benutzen",
    "Libraries are toolboxes - don't build hammers, just use them": "Bibliotheken sind Werkzeugkästen - baue keine Hämmer, benutze sie einfach",
    "Without Libraries": "Ohne Bibliotheken",
    "With Libraries": "Mit Bibliotheken",
    "5 lines, reinventing the wheel": "5 Zeilen, das Rad neu erfinden",
    "1 line, tested, reliable": "1 Zeile, getestet, zuverlässig",
    "Math/Science": "Mathe/Wissenschaft",
    "Visualization": "Visualisierung",
    "Files/Automation": "Dateien/Automatisierung",
    "Arrays, matrices": "Arrays, Matrizen",
    "Engineering calcs": "Ingenieur-Berechnungen",
    "Data tables": "Datentabellen",
    "Basic math ops": "Grundlegende Mathe-Ops",
    "Charts, plots": "Diagramme, Plots",
    "Interactive plots": "Interaktive Plots",
    "Statistical viz": "Statistische Viz",
    "File operations": "Dateioperationen",
    "Read/write JSON": "JSON lesen/schreiben",
    "Spreadsheets": "Tabellen",
    "Dates/times": "Datum/Zeit",
    'Ask AI: "What library should I use to [task]?" or "Show me how to use [library] for [goal]"': 'Frag KI: "Welche Bibliothek für [Aufgabe]?" oder "Zeig mir wie man [Bibliothek] für [Ziel] benutzt"',
    "Stand on shoulders of giants - use libraries!": "Auf den Schultern von Riesen stehen - benutze Bibliotheken!",

    # 15-1-data-structures.svg
    "Ways to organize multiple pieces of data": "Wege, mehrere Datenteile zu organisieren",
    "LISTE": "LISTE",
    "Geordnete Sammlung": "Geordnete Sammlung",
    "WÖRTERBUCH": "WÖRTERBUCH",
    "Schlüssel-Wert-Paare": "Schlüssel-Wert-Paare",
    "TUPLE": "TUPEL",
    "Fixed, unchangeable list": "Feste, unveränderbare Liste",
    "Access by position: bolt_sizes[0]": "Zugriff nach Position: bolt_sizes[0]",
    "Add/remove items": "Elemente hinzufügen/entfernen",
    "Like a shopping list": "Wie eine Einkaufsliste",
    "Access by name: bolt[\"grade\"]": "Zugriff nach Name: bolt[\"grade\"]",
    "Like a real dictionary: word → definition": "Wie ein echtes Wörterbuch: Wort → Definition",
    "Can't change after creation": "Nach Erstellung nicht änderbar",
    "Good for coordinates, constants": "Gut für Koordinaten, Konstanten",
    "Like a sealed envelope": "Wie ein versiegelter Umschlag",
    "When To Use What": "Wann was benutzen",
    "Collection of similar items": "Sammlung ähnlicher Elemente",
    "Need to add/remove items": "Elemente hinzufügen/entfernen nötig",
    "bolt_sizes, measurements": "bolt_sizes, measurements",
    "Named properties": "Benannte Eigenschaften",
    "Need to look up by name": "Nach Namen nachschlagen nötig",
    "bolt specs, config settings": "Schrauben-Specs, Konfig-Einstellungen",
    "Fixed group of values": "Feste Wertegruppe",
    "Should never change": "Sollte sich nie ändern",
    "x,y,z coordinates": "x,y,z Koordinaten",
    'Ask AI: "What data structure should I use for [description]?"': 'Frag KI: "Welche Datenstruktur für [Beschreibung]?"',
    "Right structure = Cleaner, faster code": "Richtige Struktur = Sauberer, schnellerer Code",

    # 16-1-testing.svg
    "Verifying your code actually works": "Überprüfen, ob dein Code wirklich funktioniert",
    "Testing = Quality control for code (like checking parts before assembly)": "Testen = Qualitätskontrolle für Code (wie Teile vor der Montage prüfen)",
    "Manual Testing": "Manuelles Testen",
    "Automated Testing": "Automatisiertes Testen",
    "Edge Case Testing": "Grenzfall-Testen",
    "Run the code": "Code ausführen",
    "Check the output": "Ausgabe prüfen",
    "Try different inputs": "Verschiedene Eingaben testen",
    "Good for quick checks": "Gut für schnelle Prüfungen",
    "Write test code": "Testcode schreiben",
    "Runs automatically": "Läuft automatisch",
    "Catches regressions": "Findet Regressionen",
    "Good for reliability": "Gut für Zuverlässigkeit",
    "Empty inputs": "Leere Eingaben",
    "Extreme values": "Extreme Werte",
    "Invalid data": "Ungültige Daten",
    "Good for robustness": "Gut für Robustheit",
    "Simple Test Example": "Einfaches Testbeispiel",
    "Test Results": "Testergebnisse",
    "PASS": "BESTANDEN",
    "FEHLER": "FEHLER",
    "Code works!": "Code funktioniert!",
    "Fix needed": "Korrektur nötig",
    'Ask AI: "Write tests for this function"': 'Frag KI: "Schreibe Tests für diese Funktion"',
    "Test before trusting: known input + expected output = verification": "Vor dem Vertrauen testen: bekannte Eingabe + erwartete Ausgabe = Verifizierung",
    "Tested code = Trusted code": "Getesteter Code = Vertrauenswürdiger Code",
}

def translate_svg(input_path: Path, output_path: Path):
    """Translate an SVG file from English to German."""
    with open(input_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Sort translations by length (longest first) to avoid partial replacements
    sorted_translations = sorted(TRANSLATIONS.items(), key=lambda x: len(x[0]), reverse=True)

    for english, german in sorted_translations:
        # Replace text content between > and <
        content = re.sub(
            f'>{re.escape(english)}<',
            f'>{german}<',
            content
        )

    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)

    return True

def main():
    source_dir = PROJECT_DIR / "diagrams" / "source"
    output_dir = PROJECT_DIR / "diagrams" / "source" / "de"

    svg_files = sorted(source_dir.glob("*.svg"))

    print(f"Found {len(svg_files)} SVG files to translate\n")

    for svg_file in svg_files:
        output_file = output_dir / svg_file.name
        print(f"Translating: {svg_file.name}")
        translate_svg(svg_file, output_file)
        print(f"  → {output_file.name}")

    print(f"\nTranslated {len(svg_files)} files to {output_dir}")

if __name__ == "__main__":
    main()
